name: GitHub Classroom Workflow

on: [push]

jobs:
  build:
    strategy:
      matrix:
        node-version: [13.x]
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: education/autograding@v1
